import frappe


def execute():

    data = [
        {
            "accounts": [],
            "accrual_component": 0,
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "arrear_component": 0,
            "component_type": "",
            "custom_component_sub_type": "Fixed",
            "custom_is_accrual": 0,
            "custom_is_arrear": 0,
            "custom_is_part_of_appraisal": 0,
            "custom_is_part_of_ctc": 0,
            "custom_sub_category": "",
            "custom_tax_exemption_applicable_based_on_regime": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 1,
            "disabled": 0,
            "do_not_include_in_accounts": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "final_cycle_accrual_payout": 0,
            "formula": '(\n    60 if (custom_lwf and custom_lwf_state == "Goa" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    34 if (custom_lwf and custom_lwf_state == "Haryana" and custom_frequency == "Monthly") else\n    3 if (custom_lwf and custom_lwf_state == "West Bengal" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    2 if (custom_lwf and custom_lwf_state == "Telangana" and custom_frequency == "Yearly") else\n    20 if (custom_lwf and custom_lwf_state == "Tamil Nadu" and custom_frequency == "Yearly") else\n    5 if (custom_lwf and custom_lwf_state == "Punjab" and custom_frequency == "Monthly") else\n    10 if (custom_lwf and custom_lwf_state == "Odisha" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    25 if (custom_lwf and custom_lwf_state == "Maharashtra" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    10 if (custom_lwf and custom_lwf_state == "Madhya Pradesh" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    50 if (custom_lwf and custom_lwf_state == "Kerala" and custom_frequency == "Monthly") else\n    50 if (custom_lwf and custom_lwf_state == "Karnataka" and custom_frequency == "Yearly" and getdate(start_date).month == 12) else\n    15 if (custom_lwf and custom_lwf_state == "Chattisgarh" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    5 if (custom_lwf and custom_lwf_state == "Chandigarh" and custom_frequency == "Monthly") else\n    6 if (custom_lwf and custom_lwf_state == "Gujarat" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    0.75 if (custom_lwf and custom_lwf_state == "Delhi" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    30 if (custom_lwf and custom_lwf_state == "Andhra Pradesh" and custom_frequency == "Yearly" and getdate(start_date).month == 12) else\n    0\n)',  # noqa: E501
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "modified": "2026-02-22 19:17:09.739525",
            "name": "LWF (Employee)",
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "LWF (Employee)",
            "salary_component_abbr": "LWFE",
            "statistical_component": 0,
            "type": "Deduction",
            "variable_based_on_taxable_salary": 0,
            "custom_regime": "All",
        },
        {
            "accounts": [],
            "accrual_component": 0,
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "arrear_component": 0,
            "component_type": "",
            "custom_component_sub_type": "Fixed",
            "custom_is_accrual": 0,
            "custom_is_arrear": 0,
            "custom_is_part_of_appraisal": 0,
            "custom_is_part_of_ctc": 0,
            "custom_sub_category": "",
            "custom_tax_exemption_applicable_based_on_regime": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 1,
            "disabled": 0,
            "do_not_include_in_accounts": 0,
            "do_not_include_in_total": 1,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "final_cycle_accrual_payout": 0,
            "formula": '(\n    180 if (custom_lwf and custom_lwf_state == "Goa" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    68 if (custom_lwf and custom_lwf_state == "Haryana" and custom_frequency == "Monthly") else\n    30 if (custom_lwf and custom_lwf_state == "West Bengal" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    5 if (custom_lwf and custom_lwf_state == "Telangana" and custom_frequency == "Yearly") else\n    40 if (custom_lwf and custom_lwf_state == "Tamil Nadu" and custom_frequency == "Yearly") else\n    20 if (custom_lwf and custom_lwf_state == "Punjab" and custom_frequency == "Monthly") else\n    20 if (custom_lwf and custom_lwf_state == "Odisha" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    75 if (custom_lwf and custom_lwf_state == "Maharashtra" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    30 if (custom_lwf and custom_lwf_state == "Madhya Pradesh" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    50 if (custom_lwf and custom_lwf_state == "Kerala" and custom_frequency == "Monthly") else\n    100 if (custom_lwf and custom_lwf_state == "Karnataka" and custom_frequency == "Yearly" and getdate(start_date).month == 12) else\n    45 if (custom_lwf and custom_lwf_state == "Chattisgarh" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    20 if (custom_lwf and custom_lwf_state == "Chandigarh" and custom_frequency == "Monthly") else\n    12 if (custom_lwf and custom_lwf_state == "Gujarat" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    2.25 if (custom_lwf and custom_lwf_state == "Delhi" and custom_frequency == "Half-Yearly" and getdate(start_date).month == 6) else\n    70 if (custom_lwf and custom_lwf_state == "Andhra Pradesh" and custom_frequency == "Yearly" and getdate(start_date).month == 12) else\n    0\n)',  # noqa: E501
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "modified": "2026-02-22 19:27:42.201208",
            "name": "LWF (Employer)",
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "LWF (Employer)",
            "salary_component_abbr": "LWFER",
            "statistical_component": 0,
            "type": "Deduction",
            "variable_based_on_taxable_salary": 0,
        },
        {
            "accounts": [],
            "accrual_component": 0,
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "arrear_component": 0,
            "component_type": "Professional Tax",
            "custom_component_sub_type": "Fixed",
            "custom_is_accrual": 0,
            "custom_is_arrear": 0,
            "custom_is_part_of_appraisal": 0,
            "custom_is_part_of_ctc": 0,
            "custom_sub_category": "",
            "custom_tax_exemption_applicable_based_on_regime": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 1,
            "disabled": 0,
            "do_not_include_in_accounts": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "final_cycle_accrual_payout": 0,
            "formula": '((300 if gross_pay > 250000 and getdate(start_date).month == 2 else 200 if gross_pay > 250000 else 0) if custom_state == "Karnataka" else\n(200 if gross_pay > 302400 else 0) if custom_state == "Punjab" else\n0 if custom_state == "Rajasthan" else\n(0 if gross_pay <= 18750 else 125 if gross_pay <= 25000 else (174 if getdate(start_date).month == 2 else 166) if gross_pay <= 33333 else (212 if getdate(start_date).month == 2 else 208)) if custom_state == "Madhya Pradesh" else\n(0 if gross_pay <= 15000 else 150 if gross_pay <= 20000 else 200) if custom_state == "Telangana" else\n(0 if gross_pay <= 25000 else 100 if gross_pay <= 41666 else 150 if gross_pay <= 66666 else 175 if gross_pay <= 83333 else 208) if custom_state == "Jharkhand" else\n(0 if gross_pay <= 40000 else 30 if gross_pay <= 50000 else 60 if gross_pay <= 60000 else 90 if gross_pay <= 80000 else 100 if gross_pay <= 100000 else 120 if gross_pay <= 150000 else 150 if gross_pay <= 200000 else 180 if gross_pay <= 250000 else 190 if gross_pay <= 300000 else 200) if custom_state == "Chhattisgarh" else\n(0 if gross_pay <= 25000 else (87 if getdate(start_date).month == 2 else 83) if gross_pay <= 41667 else (163 if getdate(start_date).month == 2 else 167) if gross_pay <= 83333 else (212 if getdate(start_date).month == 2 else 208)) if custom_state == "Bihar" else\n(0 if gross_pay <= 10000 else 150 if gross_pay <= 14999 else 180 if gross_pay <= 24999 else 208) if custom_state == "Assam" else\n(1250/6) if custom_state == "Tamil Nadu" else\n(0 if ((gender == "Male" and gross_pay <= 7500) or (gender == "Female" and gross_pay <= 25000)) else 175 if (gender == "Male" and gross_pay <= 10000) else (300 if getdate(start_date).month == 2 else 200)) if custom_state == "Maharashtra" else\n(0 if custom_fixed_gross_annual/12 <= 10000 else 110 if custom_fixed_gross_annual/12 <= 15000 else 130 if custom_fixed_gross_annual/12 <= 25000 else 150 if custom_fixed_gross_annual/12 <= 40000 else 200) if custom_state == "West Bengal" else\n(0 if gross_pay <= 15000 else 150 if gross_pay <= 20000 else 200) if custom_state == "Andhra Pradesh" else\n(0 if gross_pay <= 25000 else 200) if custom_state == "Gujarat" else\n0)',  # noqa: E501
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "modified": "2026-02-22 19:51:28.547645",
            "name": "Professional Tax",
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "Professional Tax",
            "salary_component_abbr": "PT",
            "statistical_component": 0,
            "type": "Deduction",
            "variable_based_on_taxable_salary": 0,
        },
        {
            "accounts": [],
            "accrual_component": 0,
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "arrear_component": 0,
            "component_type": "Provident Fund",
            "custom_component_sub_type": "Fixed",
            "custom_is_accrual": 0,
            "custom_is_arrear": 0,
            "custom_is_part_of_appraisal": 0,
            "custom_is_part_of_ctc": 0,
            "custom_sub_category": "",
            "custom_tax_exemption_applicable_based_on_regime": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 1,
            "disabled": 0,
            "do_not_include_in_accounts": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "final_cycle_accrual_payout": 0,
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "modified": "2026-02-22 19:51:28.547645",
            "name": "Provident Fund",
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "Provident Fund",
            "salary_component_abbr": "PF",
            "statistical_component": 0,
            "type": "Deduction",
            "variable_based_on_taxable_salary": 0,
        },
        {
            "accounts": [],
            "accrual_component": 0,
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "arrear_component": 0,
            "component_type": "NPS",
            "custom_component_sub_type": "Fixed",
            "custom_is_accrual": 0,
            "custom_is_arrear": 0,
            "custom_is_part_of_appraisal": 0,
            "custom_is_part_of_ctc": 1,
            "custom_sub_category": "",
            "custom_tax_exemption_applicable_based_on_regime": 1,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 1,
            "disabled": 0,
            "do_not_include_in_accounts": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "custom_regime": "All",
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "final_cycle_accrual_payout": 0,
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 1,
            "max_benefit_amount": 0.0,
            "modified": "2026-02-22 19:51:28.547645",
            "name": "NPS",
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "NPS",
            "salary_component_abbr": "NPS",
            "statistical_component": 0,
            "type": "Earning",
            "variable_based_on_taxable_salary": 0,
        },
        {
            "accounts": [],
            "accrual_component": 0,
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "arrear_component": 0,
            "component_type": "ESIC",
            "custom_component_sub_type": "Fixed",
            "custom_is_accrual": 0,
            "custom_is_arrear": 0,
            "custom_is_part_of_appraisal": 0,
            "custom_is_part_of_ctc": 0,
            "custom_sub_category": "",
            "custom_tax_exemption_applicable_based_on_regime": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 1,
            "disabled": 0,
            "do_not_include_in_accounts": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "final_cycle_accrual_payout": 0,
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "modified": "2026-02-22 19:51:28.547645",
            "name": "ESIC",
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "ESIC",
            "salary_component_abbr": "ESIC",
            "statistical_component": 0,
            "type": "Deduction",
            "variable_based_on_taxable_salary": 0,
        },
        {
            "accounts": [],
            "accrual_component": 0,
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "arrear_component": 0,
            "component_type": "",
            "custom_component_sub_type": "Fixed",
            "custom_is_accrual": 0,
            "custom_is_arrear": 0,
            "custom_is_part_of_appraisal": 0,
            "custom_is_part_of_ctc": 0,
            "custom_sub_category": "",
            "custom_tax_exemption_applicable_based_on_regime": 0,
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 1,
            "disabled": 0,
            "do_not_include_in_accounts": 0,
            "do_not_include_in_total": 1,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "final_cycle_accrual_payout": 0,
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 0,
            "max_benefit_amount": 0.0,
            "modified": "2026-02-22 19:51:28.547645",
            "name": "Provident Fund (Employer)",
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "Provident Fund (Employer)",
            "salary_component_abbr": "PFE",
            "statistical_component": 0,
            "type": "Deduction",
            "variable_based_on_taxable_salary": 0,
        },
        {
            "accounts": [],
            "accrual_component": 0,
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "arrear_component": 0,
            "custom_component_sub_type": "Fixed",
            "custom_is_accrual": 0,
            "custom_is_arrear": 0,
            "custom_is_part_of_appraisal": 0,
            "custom_is_part_of_ctc": 0,
            "custom_sub_category": "",
            "custom_tax_exemption_applicable_based_on_regime": 1,
            "custom_regime": "All",
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 0,
            "disabled": 0,
            "do_not_include_in_accounts": 0,
            "do_not_include_in_total": 1,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "final_cycle_accrual_payout": 0,
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 1,
            "max_benefit_amount": 0.0,
            "modified": "2026-02-22 19:51:28.547645",
            "name": "Car Perquisite",
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "Car Perquisite",
            "salary_component_abbr": "CP",
            "statistical_component": 0,
            "type": "Earning",
            "variable_based_on_taxable_salary": 0,
            "formula": "custom_car_perquisite_as_per_rules if custom_car_perquisite else 0",
        },
        {
            "accounts": [],
            "accrual_component": 0,
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "arrear_component": 0,
            "custom_component_sub_type": "Fixed",
            "custom_is_accrual": 0,
            "custom_is_arrear": 0,
            "custom_is_part_of_appraisal": 0,
            "custom_is_part_of_ctc": 0,
            "custom_component_sequence": "10",
            "custom_sub_category": "",
            "custom_tax_exemption_applicable_based_on_regime": 1,
            "custom_regime": "All",
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 0,
            "disabled": 0,
            "do_not_include_in_accounts": 0,
            "do_not_include_in_total": 1,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "final_cycle_accrual_payout": 0,
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 1,
            "max_benefit_amount": 0.0,
            "modified": "2026-02-22 19:51:28.547645",
            "name": "Driver Perquisite",
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "Driver Perquisite",
            "salary_component_abbr": "DP",
            "statistical_component": 0,
            "type": "Earning",
            "variable_based_on_taxable_salary": 0,
            "custom_perquisite": 1,
            "formula": "custom_driver_perquisite_as_per_rules if custom_driver_provided_by_company else 0",
        },
        {
            "accounts": [],
            "accrual_component": 0,
            "amount": 0.0,
            "amount_based_on_formula": 1,
            "arrear_component": 0,
            "component_type": "LTA",
            "custom_component_sub_type": "Fixed",
            "custom_is_accrual": 0,
            "custom_is_arrear": 0,
            "custom_is_part_of_appraisal": 0,
            "custom_is_part_of_ctc": 0,
            "custom_component_sequence": "10",
            "custom_sub_category": "",
            "custom_tax_exemption_applicable_based_on_regime": 1,
            "custom_regime": "All",
            "deduct_full_tax_on_selected_payroll_date": 0,
            "depends_on_payment_days": 1,
            "disabled": 0,
            "do_not_include_in_accounts": 0,
            "do_not_include_in_total": 0,
            "docstatus": 0,
            "doctype": "Salary Component",
            "exempted_from_income_tax": 0,
            "final_cycle_accrual_payout": 0,
            "is_flexible_benefit": 0,
            "is_income_tax_component": 0,
            "is_tax_applicable": 1,
            "max_benefit_amount": 0.0,
            "modified": "2026-02-22 19:51:28.547645",
            "name": "Leave Travel Allowance",
            "remove_if_zero_valued": 1,
            "round_to_the_nearest_integer": 0,
            "salary_component": "Leave Travel Allowance",
            "salary_component_abbr": "LTA",
            "statistical_component": 0,
            "type": "Earning",
            "variable_based_on_taxable_salary": 0,

        },
    ]

    for d in data:
        insert_or_update(d)


def insert_or_update(d):

    if not frappe.db.exists("Salary Component", d["name"]):
        doc = frappe.new_doc("Salary Component")
        doc.update(d)
        doc.insert()

    else:
        doc = frappe.get_doc("Salary Component", d["name"])
        doc.update(
            {
                "formula": d.get("formula"),
                "type": d.get("type"),
                "component_type": d.get("component_type"),
                "depends_on_payment_days": d.get("depends_on_payment_days"),
            }
        )

        doc.save()
